### ISSUE TITLE
兄弟，顶不住了，你还有起床时间记录_旧版本 的代码吗？

### ISSUE THREAD

**Issue by moreluck-Yu** [skipmaple/Kobe#4]
现在的输出内容，只有时间 没有年月日，感觉怪怪的。  
而且我也比较喜欢诗歌，加上每日一诗 也挺不错的。

一开始我自己 尝试去写，最后 总是输出 相同的诗句。。。
你能我看看吗，谢谢！！！

**Comment by skipmaple** [comment]
今天的起床时间是--8:51AM

 现在的天气是 23.2 °C, 大雨

**Comment by skipmaple** [comment]
今天的起床时间是--9:18AM

 现在的天气是 23.4 °C, 小雨

**Comment by skipmaple** [comment]
今天的起床时间是--10:30AM

 现在的天气是 23.7 °C, 中雨
